module.exports = [
  {
    name: "Welcome to the Arena",
    description: "Play your first game",
    xp: 500,
    coins: 50,
    stat: "games_played",
    requiredAmount: 1,
    hidden: false,
  },
  {
    name: "Go outside",
    description: "Win 1 game",
    xp: 500,
    coins: 50,
    stat: "first_place",
    requiredAmount: 1,
    hidden: false,
  },
  {
    name: "Touch Grass",
    description: "Win 10 games",
    xp: 500,
    coins: 30,
    stat: "first_place",
    requiredAmount: 5,
    hidden: false,
  },
  {
    name: "You've been in a coma for 20 years and we're trying a new technique, please wake up",
    description: "Win 20 games",
    xp: 2000,
    coins: 125,
    stat: "first_place",
    requiredAmount: 10,
    hidden: false,
  },
  {
    name: "Rounding up",
    description: "Win 100 rounds",
    xp: 500,
    coins: 50,
    stat: "won_rounds",
    requiredAmount: 1,
    hidden: false,
  },
  {
    name: "Winding down",
    description: "Win 1000 rounds",
    xp: 500,
    coins: 30,
    stat: "won_rounds",
    requiredAmount: 5,
    hidden: false,
  },
  {
    name: "Played too much",
    description: "Win 9999 rounds",
    xp: 2000,
    coins: 125,
    stat: "won_rounds",
    requiredAmount: 10,
    hidden: false,
  },
  {
    name: "Gaben",
    description: "Get a Gaben",
    xp: 500,
    coins: 50,
    stat: "gabens",
    requiredAmount: 1,
    hidden: false,
  },
  {
    name: "Gabe Newell",
    description: "Get 100 Gabens",
    xp: 500,
    coins: 50,
    stat: "gabens",
    requiredAmount: 100,
    hidden: false,
  },
  {
    name: "Balls",
    description: "Guess what password Sunsfan uses in his private lobbies",
    xp: 500,
    coins: 50,
    stat: "horse",
    requiredAmount: 1,
    hidden: false,
  },
];
