const Players = require("../db/players");

const usernames = [
  "Carcosa",
  "Alpha Omega Pepega",
  "Hazy",
  "Achair",
  "Ju5b3n",
  "Oompa Loompa",
  "BaneMage",
  "lexysoda",
  "You're Dead",
  "wasdqe",
  "kamikaze",
  "Ñ Ð½Ðµ Ð±Ð¾ÑŽÑÑŒ Ñ‚ÐµÐ±Ñ",
  "faraon",
  "Q",
  "dangerous biker gangboss of hell",
  "LesGrossman",
  "savage.",
  "vermouthh23",
  "Shefeto",
  "Huchimama",
  "Muad'Dib",
  "Tsoiba",
  "24",
  "Captain",
  "Yud-Hahaha",
  "NeDoMaliar",
  "Turtle of Disrespect",
  "Tsuki~",
  "Mr. Airplane",
  "69",
  "upingifeed",
  "METROMAN",
  "BenetrahKiberdroch",
  "A-z Art",
  "THE other ONE",
  "kykyxa",
  "Rak",
  "Ferbu^cL",
  "Schneider",
  "n3.wcyd",
  "MangoKing",
  "908-",
  "twitch.tvdezaoasm_",
  "Rimuru",
  "Ben Dover ~~~â±­Íž Ì¶Íž Ì¶Íž ï»ï®ž",
  "tunchie",
  "neoxa.Juruto",
  "eztuyz",
  "NeverHeard",
  "çŸ¥ã‚‰ãªã„",
  "Jung-Hak",
  "33",
  "hajime",
  "â™ªMike Litorisâ™ª",
  "Casi",
  "akyto_me",
  "Sullen",
  "rifuki",
  "sunlean",
  "Dr.KS",
  "Farewell Ballad",
  "MaskOnSocksOFF",
  "HAPPY NEW YEAR 2023!!!!!",
  "Zod Exarion",
  "Dragonus",
  "Ð ÐÐ‘ Ð¢Ð’ÐžÐ¯ Ð“ÐžÐ¡ÐŸÐžÐ”Ð˜Ð",
  "BatEatBanana",
  "bandsman3",
  "mqs",
  "ugamerzz1",
  "JimOne",
  "akm22akm",
  "Z E N",
  "Rozas",
  "eace",
  "godzinfinity3",
  "pysiaz",
  "insania",
  "makrocell",
  "Youmadlolcat",
  "OGmz",
  "mangateng",
  "Jackira24",
  "Crazyrudralive",
  "ariajayawinata",
  "boygamer",
  "Eii Le Mao",
  "Thun",
  "Wh1stler",
  "SezR",
  "TeamCapitan",
  "Meinhart Erschwanz",
  "Zer0",
  "FBI CLAN",
  "Daniel Avacado",
  "Murmel",
  "junglle",
];

async function getMMRFromUsernames() {
  try {
    for (const username of usernames) {
      const players = await Players.getPlayersWithName(username);
      const mmrs = players.map((row) => row.mmr);
      const mmrString = mmrs.length > 0 ? mmrs.join(", ") : "null";
      console.log(`${username}, ${mmrString}`);
    }
  } catch (error) {
    throw error;
  }
}

(async function () {
  await getMMRFromUsernames();
})();
