const Players = require("../db/players");

const usernames = [
  "TangoMangoPango",
  "I'm Banana Man",
  ";) Meki",
  "6løød & 9øre",
  "Lemonguard",
  "october",
  "Noilil",
  "boor",
  "薄乐扬",
  "Chocs",
  "ROMA INVICTA",
  "kykyxa",
  "Kevin",
  "Mr. Airplane",
  "Yorushika`",
  "ninjaninjaninja",
  "Turtle of Disrespect",
  "justlovedota1",
  "Huchimama",
  "n3.wcyd",
  "Ferbu^cL",
  "sverð",
  "bandsman3",
  "mdp675",
  "Frippsen",
  "Shylock",
  "Slec",
  "Bobob",
  "dangerous biker gangboss of hell",
  "lvlup",
  "METROMAN",
  "Sometimes Sad",
  "Baromet",
  "Makima",
  "Would you wait for me?",
  "Anastasia",
  "subliminal meat",
  "Boomerang Boy",
  "Optional",
  "Utopia Rising",
  "Cute.Cryos",
  "Ichigo",
  "MEGAMIND",
  "Kidsane",
  "SAD BOI",
  "Asfaloth",
  "Jrm",
  "HandOfBlue",
  "Knappkin",
  "olland0",
  "i",
  "SIDESHOP MAN ALL DAY",
  "Siege",
  "TataMuran___GODMODE:ON",
  "Jung-Hak",
  "ZaZZiiee",
  "focus on happiness.ikjxl",
  "Ladde",
  "JiePang",
  "Jamesth007",
  "aq.",
  "鱼丸粗面",
  "hm kk",
  "RONNIE PICKERING",
  "Sullen",
  "Gwynblade",
  "Du bist Weltmeister!!",
  "ImFineTill69",
  "Delagore",
  "Dr.KS",
  "Revan",
  "Yossarian",
  "Hunter",
  "Hunt3rseeker",
  "DigDoja",
  "cdxliv",
  "HAPPY NEW YEAR 2023!!!!!",
  "rosita te estrano",
  "𐂃𐂃",
  "No me hables",
  "Rabbit",
  "worst player ever",
  "Captain",
  "rkzromantea",
  "shigueo'",
  "insomniac",
  "番茄萝卜",
  "anastasia_romanchuk777",
  "Finzki",
  "Carcosa",
  "Myrddin",
  "VioletMamba",
  "Paddawan",
  "Hazy",
  "Ромка Бандит",
  "sheesh",
  "bikedog",
  "Akapella",
  "hexbug lover",
  "Makarektz",
  "Lev Vetdre",
  "Opticor",
  "BullFrog",
  "grettenbac",
  "sjkuksee",
  "Jaopraya34",
  "ลูเเม้วอิน",
  "RORO",
  "Despairus Maximus",
  "Vladislav",
  "Daan",
  "masakiprofa",
  "Light horse",
  "rothbardie",
  "Fish",
  "Lily of the Valley",
  "Webster",
  "Poopscerd1111",
  "FattyMcGee!",
  "Abstemious Jeff",
  "Stakks",
  "SweetRain",
  "ANAK NI GABEN",
  "FEAR OF GOD",
  "Man of Culture",
  "Cavalier",
  "jobeeezy",
  "WaitingForLove",
  "bigdaddymate",
  "Kesh",
  "MangoKing",
  "BlackBlink",
  "Eii Le Mao",
  "ego1st",
  "AnimaNeo™",
  "Radish Man",
  "908",
  "Rimuru",
  "SMOOTHMAN",
  "Bärenmarke",
  "JesusWillBeBack",
  "aryacikal",
  "Eijix",
  "4fun.Juruboy",
  "Kambeng",
  "CD",
  "mar4el_tv",
  "THE other ONE",
  "DON EL | NICOMEDES",
  "hxtehxtehxtehxte",
  "闽院之光",
  "Sorrenzo",
  "watercrow",
  "control",
  "lagolicious",
  "dj_chaled",
  "ram0n",
  "Choerry",
  "Lufkin!",
  "ooapfel_saftoo",
  "Inzou_VZ",
  "jack_k3",
  "panza.inc",
  "ARTES",
  "poiqwepoiqwe2",
  "Pokes N Dotes",
  "OmegaDIMC",
  "Yoo",
  "tree_bark",
  "37-32",
  "Google Assistant",
  "MyGoodMate_",
  "kaoru mitoma",
  "Singe",
  "silentshadow",
  ".",
  "yaksam- nljs",
  "chabbal23",
  "Mr. Pink",
  "NeeNein",
  "Dumbbasket",
];

async function getMMRFromUsernames() {
  try {
    for (const username of usernames) {
      const players = await Players.getPlayersWithName(username);
      const mmrs = players.map((row) => row.mmr);
      const mmrString = mmrs.length > 0 ? mmrs.join(", ") : "null";
      console.log(`${username}, ${mmrString}`);
    }
  } catch (error) {
    throw error;
  }
}

(async function () {
  await getMMRFromUsernames();
})();
