module.exports = [
  {
    cosmetic_name: "announcer1",
    cosmetic_type: "Announcer",
    equip_group: "announcer",
    cost_coins: 0,
    rarity: "Common",
  },
  {
    cosmetic_name: "border1",
    cosmetic_type: "Avatar",
    equip_group: "avatar",
    cost_coins: -1,
    rarity: "",
  },
  {
    cosmetic_name: "border2",
    cosmetic_type: "Avatar",
    equip_group: "avatar",
    cost_coins: -1,
    rarity: "",
  },
  {
    cosmetic_name: "border3",
    cosmetic_type: "Avatar",
    equip_group: "avatar",
    cost_coins: -1,
    rarity: "",
  },
  {
    cosmetic_name: "border4",
    cosmetic_type: "Avatar",
    equip_group: "avatar",
    cost_coins: -1,
    rarity: "",
  },
  {
    cosmetic_name: "border5",
    cosmetic_type: "Avatar",
    equip_group: "avatar",
    cost_coins: -1,
    rarity: "",
  },
  {
    cosmetic_name: "chest1",
    cosmetic_type: "Chest",
    cost_coins: 100,
    equip_group: "",
    rarity: "Common",
  },
  {
    cosmetic_name: "chest2",
    cosmetic_type: "Chest",
    cost_coins: 200,
    equip_group: "",
    rarity: "Uncommon",
  },
  {
    cosmetic_name: "chest3",
    cosmetic_type: "Chest",
    cost_coins: 400,
    equip_group: "",
    rarity: "Rare",
  },
  {
    cosmetic_name: "chest4",
    cosmetic_type: "Chest",
    cost_coins: 1000,
    equip_group: "",
    rarity: "Mythical",
  },
  {
    cosmetic_name: "chest5",
    cosmetic_type: "Chest",
    cost_coins: 2000,
    equip_group: "",
    rarity: "Legendary",
  },
];
